import {
  Injectable,
  ConflictException,
  NotFoundException,
  ForbiddenException,
} from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";
import { CreateAdminDto } from "./dto/create-admin.dto";
import { UpdateAdminDto } from "./dto/update-admin.dto";
import * as bcrypt from "bcrypt";
import { Role, UserStatus } from "@prisma/client";
import { AdminFilterDto } from "./dto/admin-filter.dto";
import { buildPrismaPagination } from "../common/utils/pagination.util";
import { PageMetaDto, PaginatedResponseDto } from "../common/dto/paginated-response.dto";
import { EmailService } from "src/notifications/email.service";

@Injectable()
export class AdminService {
  constructor(
    private prisma: PrismaService,
    private emailService: EmailService
  ) { }

  async create(currentUser: any, createAdminDto: CreateAdminDto) {
    if (currentUser.role === Role.ADMIN) {
      if (
        createAdminDto.role === Role.SUPER_ADMIN ||
        createAdminDto.role === Role.ADMIN
      ) {
        throw new ForbiddenException(
          "Admins cannot create other Admins or Super Admins",
        );
      }
    }

    const existingUser = await this.prisma.user.findUnique({
      where: { email: createAdminDto.email },
    });
    if (existingUser) {
      throw new ConflictException("User with this email already exists");
    }

    const isAutoGenerated = !createAdminDto.password;
    const plainTextPassword = createAdminDto.password || Math.random().toString(36).slice(-10) + 'Aa1!';
    const hashedPassword = await bcrypt.hash(plainTextPassword, 10);

    const userRole = createAdminDto.role || Role.ADMIN;

    const user = await this.prisma.user.create({
      data: {
        ...createAdminDto,
        password: hashedPassword,
        role: userRole,
        status: createAdminDto.status || UserStatus.ACTIVE,
        forcePasswordChange: isAutoGenerated, // force change if auto-generated
      },
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        status: true,
        createdAt: true,
      },
    });

    if (isAutoGenerated) {
      // Don't await this, let it process in background to avoid blocking request
      this.emailService.sendWelcomeEmail(user.email, plainTextPassword, user.role);
    }

    return user;
  }

  async findAll(filterDto: AdminFilterDto) {
    const { role, status, page = 1, limit = 10, sortBy, sortOrder, search } = filterDto || {};

    const where: any = {
      role: { in: [Role.ADMIN, Role.SUPER_ADMIN] },
    };

    if (role) {
      where.role = role;
    }
    if (status) {
      where.status = status;
    }

    const { skip, take, orderBy } = buildPrismaPagination(filterDto, {
      defaultOrderBy: { createdAt: "desc" },
      searchFields: ["name", "email"],
    });

    const [items, itemCount] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take,
        orderBy,
        select: {
          id: true,
          email: true,
          name: true,
          role: true,
          status: true,
          createdAt: true,
        },
      }),
      this.prisma.user.count({ where }),
    ]);

    return new PaginatedResponseDto(items, new PageMetaDto({ page, limit, itemCount }));
  }

  async findOne(id: string) {
    const user = await this.prisma.user.findUnique({
      where: { id },
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        status: true,
        createdAt: true,
      },
    });
    if (!user) throw new NotFoundException("Admin not found");
    return user;
  }

  async update(currentUser: any, id: string, updateAdminDto: UpdateAdminDto) {
    if (currentUser.role === Role.ADMIN) {
      if (
        updateAdminDto.role === Role.SUPER_ADMIN ||
        updateAdminDto.role === Role.ADMIN
      ) {
        throw new ForbiddenException(
          "Admins cannot update other Admins or Super Admins",
        );
      }
    }

    const data: any = { ...updateAdminDto };
    if (updateAdminDto.password) {
      data.password = await bcrypt.hash(updateAdminDto.password, 10);
    }
    return this.prisma.user.update({
      where: { id },
      data,
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  remove(id: string) {
    return this.prisma.user.update({
      where: { id },
      data: { status: UserStatus.INACTIVE },
    });
  }
}
