import {
  Injectable,
  ConflictException,
  NotFoundException,
  ForbiddenException,
  InternalServerErrorException,
} from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";
import { CreateAdminDto } from "./dto/create-admin.dto";
import { UpdateAdminDto } from "./dto/update-admin.dto";
import * as bcrypt from "bcrypt";
import { Role, UserStatus } from "@prisma/client";
import { AdminFilterDto } from "./dto/admin-filter.dto";
import { buildPrismaPagination } from "../common/utils/pagination.util";
import {
  PageMetaDto,
  PaginatedResponseDto,
} from "../common/dto/paginated-response.dto";
import { EmailService } from "../notifications/email.service";

@Injectable()
export class AdminService {
  constructor(
    private prisma: PrismaService,
    private emailService: EmailService,
  ) {}

  async create(currentUser: any, createAdminDto: CreateAdminDto) {
    if (currentUser.role === Role.ADMIN) {
      if (
        createAdminDto.role === Role.SUPER_ADMIN ||
        createAdminDto.role === Role.ADMIN
      ) {
        throw new ForbiddenException(
          "Admins cannot create other Admins or Super Admins",
        );
      }
    }

    const existingUser = await this.prisma.user.findUnique({
      where: { email: createAdminDto.email },
    });
    if (existingUser) {
      throw new ConflictException("User with this email already exists");
    }

    const isAutoGenerated = !createAdminDto.password;
    const plainTextPassword =
      createAdminDto.password || Math.random().toString(36).slice(-10) + "Aa1!";
    const hashedPassword = await bcrypt.hash(plainTextPassword, 10);

    const userRole = createAdminDto.role || Role.ADMIN;

    const user = await this.prisma.$transaction(async (prisma) => {
      const newUser = await prisma.user.create({
        data: {
          ...createAdminDto,
          password: hashedPassword,
          role: userRole,
          status: createAdminDto.status || UserStatus.ACTIVE,
          forcePasswordChange: isAutoGenerated, // force change if auto-generated
        },
        select: {
          id: true,
          email: true,
          name: true,
          role: true,
          status: true,
          createdAt: true,
        },
      });

      if (isAutoGenerated) {
        const emailSent = await this.emailService.sendWelcomeEmail(
          newUser.email,
          plainTextPassword,
          newUser.role,
        );

        if (!emailSent) {
          throw new InternalServerErrorException(
            "Failed to send welcome email. User creation aborted.",
          );
        }
      }

      return newUser;
    });

    return { ...user, emailSent: isAutoGenerated };
  }

  async findAll(filterDto: AdminFilterDto) {
    const {
      role,
      status,
      page = 1,
      limit = 10,
      sortBy,
      sortOrder,
      search,
    } = filterDto || {};

    const where: any = {
      role: { in: [Role.ADMIN, Role.SUPER_ADMIN] },
    };

    if (role) {
      where.role = role;
    }
    if (status) {
      where.status = status;
    }

    const { skip, take, orderBy, searchWhere } = buildPrismaPagination(
      filterDto,
      {
        defaultOrderBy: { createdAt: "desc" },
        searchFields: ["name", "email"],
      },
    );

    Object.assign(where, searchWhere);

    const [items, itemCount] = await Promise.all([
      this.prisma.user.findMany({
        where,
        skip,
        take,
        orderBy,
        select: {
          id: true,
          email: true,
          name: true,
          role: true,
          status: true,
          createdAt: true,
        },
      }),
      this.prisma.user.count({ where }),
    ]);

    return new PaginatedResponseDto(
      items,
      new PageMetaDto({ page, limit, itemCount }),
    );
  }

  async findOne(id: string) {
    const user = await this.prisma.user.findUnique({
      where: { id },
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        status: true,
        createdAt: true,
      },
    });
    if (!user) throw new NotFoundException("Admin not found");
    return user;
  }

  async update(currentUser: any, id: string, updateAdminDto: UpdateAdminDto) {
    if (currentUser.id === id) {
      if (updateAdminDto.role && updateAdminDto.role !== currentUser.role) {
        throw new ConflictException("You cannot change your own role");
      }
      if (
        updateAdminDto.status &&
        updateAdminDto.status !== UserStatus.ACTIVE
      ) {
        throw new ConflictException("You cannot deactivate your own account");
      }
    }

    if (currentUser.role === Role.ADMIN) {
      if (
        updateAdminDto.role === Role.SUPER_ADMIN ||
        updateAdminDto.role === Role.ADMIN
      ) {
        throw new ForbiddenException(
          "Admins cannot update other Admins or Super Admins",
        );
      }
    }

    const targetUser = await this.findOne(id);
    if (
      targetUser.role === Role.SUPER_ADMIN &&
      ((updateAdminDto.role !== undefined &&
        updateAdminDto.role !== Role.SUPER_ADMIN) ||
        updateAdminDto.status === UserStatus.INACTIVE)
    ) {
      const activeSuperAdmins = await this.prisma.user.count({
        where: { role: Role.SUPER_ADMIN, status: UserStatus.ACTIVE },
      });
      if (activeSuperAdmins <= 1) {
        throw new ConflictException(
          "Cannot demote or deactivate the last active SUPER_ADMIN",
        );
      }
    }

    const data: any = { ...updateAdminDto };
    if (updateAdminDto.password) {
      data.password = await bcrypt.hash(updateAdminDto.password, 10);
    }
    return this.prisma.user.update({
      where: { id },
      data,
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  async remove(currentUser: any, id: string) {
    if (currentUser.id === id) {
      throw new ConflictException("You cannot deactivate your own account");
    }

    const targetUser = await this.findOne(id);
    if (targetUser.role === Role.SUPER_ADMIN) {
      const activeSuperAdmins = await this.prisma.user.count({
        where: { role: Role.SUPER_ADMIN, status: UserStatus.ACTIVE },
      });
      if (activeSuperAdmins <= 1) {
        throw new ConflictException(
          "Cannot deactivate the last active SUPER_ADMIN",
        );
      }
    }

    return this.prisma.user.update({
      where: { id },
      data: { status: UserStatus.INACTIVE },
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        status: true,
        updatedAt: true,
      },
    });
  }
}
